env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy" 
    # - CIBW_TEST_COMMAND="python -m unittest discover -s {project}/tests"
 
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: '3.8'
      env: CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: linux
      dist: bionic
      language: python
      python: '3.7'
      env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os : linux
      dist: bionic
      language: python
      python: '3.6'
      env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: linux
      dist: bionic
      language: python
      python: '3.5'
      env: CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: osx
      language: generic
      env:
        - PYTHON=3.8.1
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: osx
      language: generic
      env:
        - PYTHON=3.7.6
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: osx
      language: generic
      env:
        - PYTHON=3.6.8
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: osx
      language: generic
      env:
        - PYTHON=3.5.4
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.6
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
      script:
        - python -m pip install cibuildwheel twine
        - python -m pip install .
        - cd tests
        - python -m unittest
        - python -m cibuildwheel --output-dir wheelhouse
