env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy" 
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/tests"
 
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: '3.8'
      env: CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
      addons:
        apt:
          packages:
          - python3-matplotlib
          - python3-h5py
    - os: linux
      dist: bionic
      language: python
      python: '3.7'
      env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
      addons:
        apt:
          packages:
          - python3-matplotlib
          - python3-h5py
    - os : linux
      dist: bionic
      language: python
      python: '3.6'
      env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
      addons:
        apt:
          packages:
          - python3-matplotlib
          - python3-h5py
    - os: linux
      dist: bionic
      language: python
      python: '3.5'
      env: CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
      addons:
        apt:
          packages:
          - python3-matplotlib
          - python3-h5py
    - os: osx
      language: generic
      env:
        - PYTHON=3.8.1
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
    - os: osx
      language: generic
      env:
        - PYTHON=3.7.6
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
    - os: osx
      language: generic
      env:
        - PYTHON=3.6.8
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
    - os: osx
      language: generic
      env:
        - PYTHON=3.5.4
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.6
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!5]-*'

script:
    - python -m pip install cibuildwheel twine
    - python -m cibuildwheel --output-dir wheelhouse
    - ls wheelhouse/
