language: python
sudo: required

env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy" 
 
matrix:
  include:
    - python: '3.8'
      os: linux
      dist: xenial
      sudo: true
      env: CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - python: '3.7'
      os: linux
      dist: xenial
      sudo: true
      env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - python: '3.6'
      os: linux
      dist: xenial
      env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - python: '3.5'
      os: linux
      dist: xenial
      env: CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.8
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.7
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.6
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.5
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!5]-*'

install:
    - python3 -m pip install cibuildwheel

script:
    - python3 -m cibuildwheel --output-dir wheelhouse
