language: python            # this works for Linux but is an error on macOS or Windows

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: yes
          python: 3.5
          env: TOXENV=py35
        - os: osx
          python: 3.5
          env: TOXENV=py35
install:   
# all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
  - pip3 install tox-travis
  - pip3 install -r requirements.txt
  - pip3 install .

# command to run tests
script: tox

branches:
  only:
    - master