env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy" 
 
matrix:
  include:
    - language: python
      sudo: required
      python: '3.8'
      os: linux
      dist: xenial
      sudo: true
      env: CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - language: python
      sudo: required
      python: '3.7'
      os: linux
      dist: xenial
      sudo: true
      env: CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - language: python
      sudo: required
      python: '3.6'
      os: linux
      dist: xenial
      env: CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - language: python
      sudo: required
      python: '3.5'
      os: linux
      dist: xenial
      env: CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.8
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.7
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.6
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - openmp
      language: generic
      env:
        - PYTHON=3.5
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_SKIP='cp[!3]?-* cp3[!5]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!8]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.6
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!7]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!6]-*'
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"
        - export CIBW_SKIP='cp[!3]?-* cp3[!5]-*'

install:
    - pip install cibuildwheel pytest

script:
    - python -m pytest 
    - python -m cibuildwheel --output-dir wheelhouse
    - ls wheelhouse/
