branches:
  only:
    - master
    - stable

env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy" 
 
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: '3.8'
      env: CIBW_BUILD='cp38-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        # - python -m pip install .
        # - cd tests
        # - python -m unittest
        # - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: linux
      dist: bionic
      language: python
      python: '3.7'
      env: CIBW_BUILD='cp37-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os : linux
      dist: bionic
      language: python
      python: '3.6'
      env: CIBW_BUILD='cp36-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: linux
      dist: bionic
      language: python
      python: '3.5'
      env: CIBW_BUILD='cp35-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: osx
      language: generic
      env:
        - PYTHON=3.8.1
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_BUILD='cp38-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - cd ..
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            twine upload wheelhouse/*.whl;
          fi
    - os: osx
      language: generic
      env:
        - PYTHON=3.7.6
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_BUILD='cp37-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - cd ..
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            twine upload wheelhouse/*.whl; 
          fi
    - os: osx
      language: generic
      env:
        - PYTHON=3.6.8
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_BUILD='cp36-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - cd ..
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            twine upload wheelhouse/*.whl; 
          fi
    - os: osx
      language: generic
      env:
        - PYTHON=3.5.4
        - CC=gcc-9
        - CXX=g++-9
        - CIBW_BUILD='cp35-*'
      addons:
        homebrew:
          packages:
            - gcc
            - libomp
      script:
        - python3 -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python3 -m pip install .
        - cd tests
        - python3 -m unittest
        - cd ..
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            twine upload wheelhouse/*.whl; 
          fi
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - export CIBW_BUILD='cp38-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.6
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - export CIBW_BUILD='cp37-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - export CIBW_BUILD='cp36-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"
        - export CIBW_BUILD='cp35-*'
      script:
        - python -m pip install cibuildwheel twine numpy Cython matplotlib seaborn
        - python -m pip install .
        - cd tests
        - python -m unittest
        - cd ..
        - python -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse/
        - if [ $TRAVIS_BRANCH == "master" ]; then
            python -m twine upload wheelhouse/*.whl; 
          fi
