name: Unittest and build on stable branch 

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install cibuildwheel 
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build with cibuildwheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
        ls wheelhouse/
      env:
        CIBW_BEFORE_BUILD: "pip install numpy"
        CIBW_BUILD: "cp36-* cp37-* cp38-*"
        CIBW_TEST_REQUIRES: "matplotlib seaborn pytest"
        CIBW_TEST_COMMAND: "cd {project}/tests && pytest"

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install cibuildwheel 
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build with cibuildwheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
        ls wheelhouse/
      env:
        CIBW_BEFORE_BUILD: "pip install numpy"
        CIBW_BUILD: "cp36-* cp37-* cp38-*"
        CIBW_TEST_REQUIRES: "matplotlib seaborn pytest"
        CIBW_TEST_COMMAND: "cd {project}/tests && pytest"

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install cibuildwheel 
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Build with cibuildwheel
      run: |
        python -m cibuildwheel --output-dir wheelhouse
        ls wheelhouse/
      env:
        CIBW_BEFORE_BUILD: "pip install numpy"
        CIBW_BUILD: "cp36-* cp37-* cp38-*"
        CIBW_TEST_REQUIRES: "matplotlib seaborn pytest"
        CIBW_TEST_COMMAND: "cd {project}/tests && pytest"
        CC: gcc-8
        CXX: g++-8
